---
- name: Question 5 setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check kubectl present
      ansible.builtin.command: which kubectl
      register: kubectl_check
      changed_when: false
      failed_when: false

    - name: Ensure prod namespace exists
      ansible.builtin.command: kubectl get ns prod
      register: prod_ns
      changed_when: false
      failed_when: false
      when: kubectl_check.rc == 0

    - name: Create prod namespace
      ansible.builtin.command: kubectl create ns prod
      when: kubectl_check.rc == 0 and prod_ns.rc != 0

    - name: Apply legacy-logger deployment
      ansible.builtin.command: kubectl -n prod apply -f "{{ playbook_dir }}/supporting/question-5/legacy-logger.yaml"
      when: kubectl_check.rc == 0
