---
- name: Question 10 setup
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Check kubectl present
      ansible.builtin.command: which kubectl
      register: kubectl_check
      changed_when: false
      failed_when: false

    - name: Apply team-a namespace
      ansible.builtin.command: kubectl apply -f "{{ playbook_dir }}/supporting/question-10/team-a-namespace.yaml"
      register: team_a_apply
      changed_when: "'unchanged' not in team_a_apply.stdout"
      when: kubectl_check.rc == 0
