apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-app
  labels:
    app: fin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-app
  template:
    metadata:
      labels:
        app: fin-app
    spec:
      containers:
      - name: app
        image: busybox:1.36
        command: ["sh", "-c", "while true; do wget -qO- http://198.51.100.20 || true; sleep 20; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-client
  labels:
    app: test-client
spec:
  containers:
  - name: client
    image: busybox:1.36
    command: ["sh", "-c", "sleep 36000"]
